---
openapi: 3.0.1
info:
  title: Generated API
  version: "1.0"
paths:
  /api/numbers:
    get:
      responses:
        200:
          description: OK
  /api/numbers/ping:
    get:
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
