# tag::adocSnippet[]
version: "3"
# tag::adocPostgres[]
services:
  database:
    image: "postgres:12.1"
    container_name: "vintage_store_books_database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=books_database
      - POSTGRES_USER=book
      - POSTGRES_PASSWORD=book
# end::adocPostgres[]
# tag::adocPrometheus[]
  monitoring:
    image: "prom/prometheus:v2.22.0"
    container_name: "vintage_store_monitoring"
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
# end::adocPrometheus[]
# tag::adocKafka[]
  zookeeper:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    container_name: "vintage_store_zookeeper"
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
  kafka:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    container_name: "vintage_store_kafka"
    command: [
        "sh", "-c",
        "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
# end::adocKafka[]
# tag::adocMongodb[]
# end::adocMongodb[]
# end::adocSnippet[]
