version: "3"
services:
  database:
    image: "postgres:12.1"
    container_name: "vintage_store_books_database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=books_database
      - POSTGRES_USER=book
      - POSTGRES_PASSWORD=book
  monitoring:
    image: "prom/prometheus:v2.21.0"
    container_name: "vintage_store_monitoring"
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
